spring:
  application:
    name: test
server:
  port: 0
dubbo:
  application:
    name: test
    id: test
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://172.16.30.130:8848
  consumer:
    check: false